# Generated by Django 5.2.1 on 2025-05-07 18:48

import myapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=100)),
                ('firstname', models.CharField(max_length=100)),
                ('othername', models.CharField(blank=True, max_length=100)),
                ('sex', models.CharField(max_length=10)),
                ('date_of_birth', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('whatsapp_name', models.CharField(blank=True, max_length=100)),
                ('nationality', models.CharField(max_length=100)),
                ('passport', models.ImageField(upload_to=myapp.models.get_file_path)),
                ('faculty', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('level_of_study', models.CharField(max_length=20)),
                ('matric_number', models.CharField(max_length=50)),
                ('permanent_address', models.TextField()),
                ('accommodation_type', models.CharField(max_length=20)),
                ('residential_address', models.TextField()),
                ('state_of_residence', models.CharField(max_length=100)),
                ('lga_of_residence', models.CharField(max_length=100)),
                ('guardian_name', models.CharField(max_length=200)),
                ('guardian_phone_number', models.CharField(max_length=20)),
                ('religion', models.CharField(max_length=20)),
                ('state_of_origin', models.CharField(max_length=100)),
                ('local_government', models.CharField(max_length=100)),
                ('skills', models.TextField(blank=True)),
                ('extracurricular_activities', models.TextField()),
                ('submission_code', models.CharField(max_length=10, unique=True)),
                ('submission_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-submission_date'],
            },
        ),
    ]
