# Generated by Django 5.1.5 on 2025-05-10 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentsubmission',
            name='jamb_reg_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='studentsubmission',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('Single', 'Single'), ('Married', 'Married')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='studentsubmission',
            name='mode_of_entry',
            field=models.CharField(blank=True, choices=[('UTME', 'UTME'), ('Direct Entry', 'Direct Entry'), ('Transfer', 'Transfer')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='studentsubmission',
            name='next_of_kin_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='studentsubmission',
            name='next_of_kin_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='studentsubmission',
            name='next_of_kin_relationship',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='studentsubmission',
            name='second_phone_number',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
